# General

SERVER_VERSION = 'dev'

# Message Types

CLIENT_HELLO = 1
CLIENT_HELLO_RESP = 1
CLIENT_EJECT = 2
CLIENT_DISCONNECT = 3
CLIENT_OBJECT_GENERATE = 4
CLIENT_OBJECT_GENERATE_RESP = 4
CLIENT_OBJECT_SET_FIELD = 5
CLIENT_OBJECT_SET_FIELD_RESP = 5